'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowRight, Sparkles, Map, Users, Camera } from 'lucide-react';

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      {/* Navigation */}
      <nav className="fixed top-0 w-full bg-white/95 backdrop-blur border-b border-slate-200 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="text-2xl font-bold text-slate-900">Reel Route</div>
          <Link href="/dashboard">
            <Button variant="ghost">Dashboard</Button>
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="pt-32 pb-20 px-4 text-center max-w-4xl mx-auto animate-fadeInUp">
        <div className="inline-flex items-center gap-2 mb-6 px-3 py-1 bg-slate-200 rounded-full animate-scale-in">
          <Sparkles className="w-4 h-4 animate-pulse-glow" />
          <span className="text-sm text-slate-700">AI-Powered Travel Planning</span>
        </div>

        <h1 className="text-5xl sm:text-6xl font-bold text-slate-900 mb-6 leading-tight text-balance animate-slideInRight">
          Your Personal AI Travel Concierge
        </h1>

        <p className="text-xl text-slate-600 mb-8 max-w-2xl mx-auto text-balance animate-slideInLeft">
          Generate beautiful itineraries, collaborate with friends, and capture memories from every trip. 
          All powered by AI.
        </p>

        <div className="flex gap-4 justify-center">
          <Link href="/dashboard">
            <Button size="lg" className="gap-2">
              Get Started <ArrowRight className="w-4 h-4" />
            </Button>
          </Link>
        </div>
      </div>

      {/* Features Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-slate-900 text-center mb-16">
            Everything you need for perfect trips
          </h2>

          <div className="grid md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="p-6 rounded-lg border border-slate-200 hover:border-slate-400 transition-all duration-300 hover:shadow-lg animate-fadeInUp hover:scale-105">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
                <Sparkles className="w-6 h-6 text-blue-600" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2">AI Itineraries</h3>
              <p className="text-slate-600">
                Get personalized itineraries generated by AI based on your travel style and preferences.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="p-6 rounded-lg border border-slate-200 hover:border-slate-400 transition-all duration-300 hover:shadow-lg animate-fadeInUp hover:scale-105" style={{ animationDelay: '0.1s' }}>
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
                <Users className="w-6 h-6 text-green-600" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2">Collaborate</h3>
              <p className="text-slate-600">
                Invite friends and family to plan trips together with real-time collaboration.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="p-6 rounded-lg border border-slate-200 hover:border-slate-400 transition-all duration-300 hover:shadow-lg animate-fadeInUp hover:scale-105" style={{ animationDelay: '0.2s' }}>
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
                <Camera className="w-6 h-6 text-purple-600" />
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2">Memory Capture</h3>
              <p className="text-slate-600">
                Upload and organize photos from your trips in one beautiful gallery.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-slate-900 text-white text-center">
        <h2 className="text-4xl font-bold mb-6">Ready to plan your next adventure?</h2>
        <p className="text-xl text-slate-300 mb-8 max-w-2xl mx-auto">
          Create your first trip in seconds and let AI handle the planning.
        </p>
        <Link href="/dashboard">
          <Button size="lg" variant="outline" className="gap-2">
            Start Planning <ArrowRight className="w-4 h-4" />
          </Button>
        </Link>
      </section>
    </main>
  );
}
